version: '3.9'

services:
  nginx_ser:
    build: ./requirements/nginx/
    ports:
     - "80:80"
    restart: always
    networks:
     - backend
    volumes:
     - wp_vol:/var/www/
  wordpress_ser:
    build: ./requirements/wordpress/
    restart: always
    networks:
     - backend
    volumes:
     - wp_vol:/var/www/

networks:
   backend:

volumes:
   wp_vol:
     driver: local
     driver_opts:
       type: 'none'
       o: 'bind'
       device: '/home/mlarboul/data/wp'
